---
abstract: 'Extractor of microdata from HTML.'
author:
  - 'cho45 <cho45@lowreal.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  JSON: 0
  Test::Differences: 0
  Test::More: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.5, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Microdata
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  HTML::Microdata:
    file: lib/HTML/Microdata.pm
    version: 0.04
requires:
  HTML::TreeBuilder::LibXML: 0
  Hash::MultiValue: 0
  JSON: 0
  Scalar::Util: 0
  URI: 0
resources:
  bugtracker: https://github.com/cho45/HTML-Microdata/issues
  homepage: https://github.com/cho45/HTML-Microdata
  repository: git://github.com/cho45/HTML-Microdata.git
version: 0.04
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
